#   Module manifest for module 'CryptoWorks'
#   Generated by: DBAKnack
[ordered]@{
    'Get-UDFIndexBlocks' = @(
        @{ RequestLimit =  5     } 
        @{ StopWatchOn  =  $true }
    )
    'New-UDFSQLCommand' = @(
        @{ InstanceName         = 'MST3K\DEVINSTANCE'}
        @{ DatabaseName         = 'CWDB'}
        @{ IntegratedSecurity   = $true}
        @{ UserName             = 'sa'}
    )
    'Invoke-UDFSQLConnection' = @(
        @{ InstanceName         = 'MST3K\DEVINSTANCE'}
        @{ DatabaseName         = 'CWDB'}
        @{ IntegratedSecurity   = $true}
        @{ UserName             = 'sa'}
    )
    'Get-ModuleVariables' = @(
        @{ DateFormat           = "yyyy-MM-dd HH:mm:ss.ff"}
    )
}