#   Module manifest for module 'CryptoWorks'
#   Generated by: DBAKnack
[ordered]@{
    'cardano' = @(
        @{ ticker =  'ADA'}
        @{ guid   = @{}}
    )
    'bitcoin' = @(
        @{ ticker =  'BTC'} 
        @{ guid   = @()}
    )
}


<#
$asset = @{}
$asset.name = @{}
$asset.name.add("Cardano",@())
$asset.name += @{bitcoin = @{}}




$asset.name.cardano += @{'indicator' = @{'rsi' = @{}}}
$asset.name.cardano += @{'indicator' = @{'MACD' = @{}}}

$asset.name.cardano.indicator.rsi.add('min',10)

$asset.name.cardano.indicator.rsi.add('max',100)


#>