-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ***** Generated by SqlDBM: CryptoWorks, v43 by dbaknack@gmail.com ****

use CWDB

DROP TABLE IF EXISTS "dbo"."Logging";
GO


-- ************************************** "dbo"."Logging"
IF NOT EXISTS (SELECT * FROM sys.tables t join sys.schemas s ON (t.schema_id = s.schema_id) WHERE s.name='dbo' and t.name='Logging')
CREATE TABLE "dbo"."Logging"
(
 "LID"                      int NOT NULL ,
 "DateTimeLogged"           datetime2(2) NOT NULL ,
 "DateTimeEvent"            datetime2(2) NOT NULL ,
 "ElapsedTime_Milliseconds" decimal(10,2) NOT NULL ,
 "FunctionName"             varchar(255) NOT NULL ,
 "StepID"                   int NOT NULL ,
 "FunctionStep"             varchar(255) NOT NULL ,
 "Level"                    varchar(255) NOT NULL ,
 "Message"                  varchar(500) NOT NULL ,


 CONSTRAINT "pk_logging" PRIMARY KEY CLUSTERED ("LID" ASC),
 CONSTRAINT "fk_logging" FOREIGN KEY ("LID")  REFERENCES "dbo"."LogLookUp"("LID")
);
GO


CREATE NONCLUSTERED INDEX "FK_111" ON "dbo"."Logging" 
 (
  "LID" ASC
 )

GO
